# Generated by Django 5.1.2 on 2024-12-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=10)),
                ('coursedesc', models.CharField(max_length=300)),
                ('totalstudents', models.IntegerField()),
            ],
        ),
    ]
