# Generated by Django 5.1.2 on 2024-12-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='createdby',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='coursename',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='totalstudents',
            field=models.IntegerField(default=0),
        ),
    ]
