# Generated by Django 5.1.2 on 2024-12-16 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0004_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 19, 41, 5, 105426)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 19, 41, 5, 105426)),
        ),
    ]
